// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcD2LrrnevRfvfO6mAYMyuQGzMGwyMXKc',
    appId: '1:205066140595:web:be97ff77fabf6518cfa9c6',
    messagingSenderId: '205066140595',
    projectId: 'fire-d3a52',
    authDomain: 'fire-d3a52.firebaseapp.com',
    storageBucket: 'fire-d3a52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOuS-Ejr84-xZsDAmVnIUYQM6EjgF_6Ns',
    appId: '1:205066140595:android:f398375c68f927abcfa9c6',
    messagingSenderId: '205066140595',
    projectId: 'fire-d3a52',
    storageBucket: 'fire-d3a52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJNMsYNym73fwh_czrtQ5LQ0foFffmoz4',
    appId: '1:205066140595:ios:70d3e5f104321342cfa9c6',
    messagingSenderId: '205066140595',
    projectId: 'fire-d3a52',
    storageBucket: 'fire-d3a52.firebasestorage.app',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJNMsYNym73fwh_czrtQ5LQ0foFffmoz4',
    appId: '1:205066140595:ios:70d3e5f104321342cfa9c6',
    messagingSenderId: '205066140595',
    projectId: 'fire-d3a52',
    storageBucket: 'fire-d3a52.firebasestorage.app',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcD2LrrnevRfvfO6mAYMyuQGzMGwyMXKc',
    appId: '1:205066140595:web:610c93fe2030a9b3cfa9c6',
    messagingSenderId: '205066140595',
    projectId: 'fire-d3a52',
    authDomain: 'fire-d3a52.firebaseapp.com',
    storageBucket: 'fire-d3a52.firebasestorage.app',
  );
}
